# Requires Zalando Postgres Operator already installed in the cluster.
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: xroad-pg
  namespace: xroad
spec:
  teamId: "xroad"
  numberOfInstances: 3
  postgresql:
    version: "16"
    parameters:
      synchronous_commit: "on"
  patroni:
    synchronous_mode: true
    synchronous_mode_strict: false
  volume:
    size: 50Gi
  users:
    xroad_admin: ["superuser", "createdb"]
    xroad_app: []
  databases:
    serverconf: xroad_app
    messagelog: xroad_app
    opmonitor: xroad_app
  # Optional: tolerations/affinity for spreading across nodes
  # tolerations:
  #   - key: "node-role.kubernetes.io/control-plane"
  #     operator: "Exists"
  #     effect: "NoSchedule"
  # nodeAffinity: {}
