# ServiceMonitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xroad-monitor
  namespace: xroad
  labels:
    app: xroad-monitor
spec:
  selector:
    matchLabels:
      app: xroad-monitor
  endpoints:
  - port: metrics
    interval: 30s
    path: /actuator/prometheus
---
# Prometheus Service for X-Road
apiVersion: v1
kind: Service
metadata:
  name: xroad-monitor
  namespace: xroad
  labels:
    app: xroad-monitor
spec:
  selector:
    app: xroad-monitor
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: xroad-grafana-dashboard
  namespace: xroad
data:
  dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "X-Road Monitoring Dashboard",
        "tags": ["xroad"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "X-Road Services Status",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=\"xroad-monitor\"}",
                "legendFormat": "Service Status"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Database Connections",
            "type": "graph",
            "targets": [
              {
                "expr": "xroad_database_connections_active",
                "legendFormat": "Active Connections"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }
---
# Fluentd ConfigMap for Log Collection
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: xroad
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/xroad/*.log
      pos_file /var/log/fluentd/xroad.log.pos
      tag xroad.logs
      format json
    </source>
    
    <match xroad.logs>
      @type elasticsearch
      host elasticsearch-service
      port 9200
      index_name xroad-logs
      type_name _doc
    </match>
---
# Fluentd DaemonSet for Log Collection
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: xroad
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: elasticsearch-service
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: http
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: fluentd-config
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
