version: '3.8'

services:
  # Central Server - Trung tâm quản lý X-Road
  cs:
    image: ${CS_IMG}
    container_name: xroad-cs
    hostname: centralserver
    restart: unless-stopped
    environment:
      - XROAD_TOKEN_PIN=${XROAD_TOKEN_PIN}
    ports:
      - "${CS_UI_PORT:-4000}:4000"   # X-Road Admin UI
      - "${CS_DB_PORT:-5432}:5432"   # PostgreSQL Database
    volumes:
      - cs_data:/var/lib/xroad
      - cs_config:/etc/xroad
      - cs_db:/var/lib/postgresql/16/main
    networks:
      - xroad-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Security Server - Máy chủ bảo mật duy nhất
  ss0:
    image: ${SS_IMG}
    container_name: xroad-ss0
    hostname: securityserver
    restart: unless-stopped
    environment:
      - XROAD_TOKEN_PIN=${XROAD_TOKEN_PIN}
      - PROXY_JMX_PORT=4299
      - SIGNER_JMX_PORT=4298
    ports:
      - "${SS_UI_PORT:-4001}:4000"   # X-Road Admin UI
      - "${SS_PROXY_HTTP_PORT:-8080}:8080"   # Proxy HTTP
      - "${SS_PROXY_HTTPS_PORT:-8443}:8443"   # Proxy HTTPS
      - "${SS_DB_PORT:-5433}:5432"   # PostgreSQL Database
      - "${SS_JMX_PROXY_PORT:-4299}:4299"   # Proxy JMX
      - "${SS_JMX_SIGNER_PORT:-4298}:4298"   # Signer JMX
    volumes:
      - ss0_data:/var/lib/xroad
      - ss0_config:/etc/xroad
      - ss0_db:/var/lib/postgresql/16/main
      - ss0_tokens:/var/lib/softhsm/tokens
    networks:
      - xroad-network
    depends_on:
      cs:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Test CA - Cơ quan chứng thực số thử nghiệm
  testca:
    image: ${CA_IMG}
    container_name: xroad-testca
    hostname: testca
    restart: unless-stopped
    ports:
      - "${CA_UI_PORT:-8888}:8888"   # CA Web Interface
      - "${CA_API_PORT:-9998}:9998"   # CA API
    volumes:
      - testca_data:/home/ca/certs
    networks:
      - xroad-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost:8888/testca/certs"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Information System - REST API Service
  isrest:
    image: wiremock/wiremock:latest
    container_name: xroad-isrest
    hostname: isrest
    restart: unless-stopped
    ports:
      - "${IS_REST_PORT:-8080}:8080"   # REST API Service
    volumes:
      - ./wiremock_mappings:/home/wiremock/mappings
    networks:
      - xroad-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost:8080/__admin/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Information System - SOAP Service
  issoap:
    image: ${IS_SOAP_IMG}
    container_name: xroad-issoap
    hostname: issoap
    restart: unless-stopped
    ports:
      - "${IS_SOAP_PORT:-8081}:8080"   # SOAP Service
    entrypoint: ["java", "-Xms64m", "-Xmx256m", "-jar", "/example-adapter.war"]
    networks:
      - xroad-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost:8080/example-adapter/Endpoint?wsdl"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Information System - OpenAPI Service
  isopenapi:
    image: ${IS_OPENAPI_IMG}
    container_name: xroad-isopenapi
    hostname: isopenapi
    restart: unless-stopped
    ports:
      - "${IS_OPENAPI_PORT:-8082}:8080"   # OpenAPI Service
    networks:
      - xroad-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost:8080/v3/api-docs"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Mail Server for notifications
  mailpit:
    image: axllent/mailpit
    container_name: xroad-mailpit
    hostname: mailpit
    restart: unless-stopped
    ports:
      - "${MAILPIT_WEB_PORT:-8025}:8025"   # Mail Web Interface
      - "${MAILPIT_SMTP_PORT:-1025}:1025"   # SMTP Server
    volumes:
      - mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: ${MAILPIT_MAX_MESSAGES:-5000}
      MP_DATABASE: /data/mailpit.db
    networks:
      - xroad-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: xroad-nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - xroad-network
    depends_on:
      - cs
      - ss0

volumes:
  cs_data:
  cs_config:
  cs_db:
  ss0_data:
  ss0_config:
  ss0_db:
  ss0_tokens:
  testca_data:
  mailpit_data:

networks:
  xroad-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
