apiVersion: v1
kind: Namespace
metadata:
  name: xroad
  labels:
    name: xroad
    app: xroad-system
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: xroad-quota
  namespace: xroad
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: xroad-limits
  namespace: xroad
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
