# Central Server Deployment
# Central Server Configuration ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: central-server-config
  namespace: xroad
data:
  xroad-central-server.conf: |
    # X-Road Central Server Configuration
    # Basic configuration for X-Road Central Server

    # Database configuration
    db.host=cs-postgres-service
    db.port=5432
    db.name=xroad_cs
    db.user=admin
    db.password=admin123

    # Server configuration
    server.host=0.0.0.0
    server.port=8080
    server.ssl.port=8443
    server.admin.port=4000

    # Logging configuration
    logging.level=INFO
    logging.file=/var/log/xroad/xroad.log

    # Security configuration
    security.enabled=true
    security.ssl.enabled=true

    # Instance configuration
    instance.identifier=EE
    instance.name=Test Instance

    # Central server specific configuration
    central-server.registration-service.enabled=true
    central-server.management-service.enabled=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-server
  namespace: xroad
  labels:
    app: central-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-server
  template:
    metadata:
      labels:
        app: central-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-1
      containers:
      - name: central-server
        image: niis/xroad-central-server:noble-7.7.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: admin
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        env:
        - name: XROAD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: xroad-admin-secret
              key: username
        - name: XROAD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: xroad-admin-secret
              key: password
        - name: XROAD_DB_HOST
          value: cs-postgres-service
        - name: XROAD_DB_PORT
          value: "5432"
        - name: XROAD_DB_PWD
          valueFrom:
            secretKeyRef:
              name: cs-db-secret
              key: password
        - name: XROAD_DATABASE_NAME
          value: xroad_cs
        - name: XROAD_LOG_LEVEL
          value: INFO
        volumeMounts:
        - name: cs-config-volume
          mountPath: /etc/xroad/
        - name: cs-config-file
          mountPath: /etc/xroad/conf.d/xroad-central-server.conf
          subPath: xroad-central-server.conf
        - name: cs-logs-volume
          mountPath: /var/log/xroad
        - name: cs-tmp-volume
          mountPath: /var/tmp/xroad
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
             volumes:
             - name: cs-config-volume
               hostPath:
                 path: /var/lib/xroad/cs-config
                 type: DirectoryOrCreate
             - name: cs-config-file
               configMap:
                 name: central-server-config
             - name: cs-logs-volume
               emptyDir: {}
             - name: cs-tmp-volume
               emptyDir: {}
      initContainers:
      - name: cs-init
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Initializing Central Server configuration..."
          mkdir -p /etc/xroad/conf.d
          mkdir -p /etc/xroad/services
          echo "Central Server initialization completed"
        volumeMounts:
        - name: cs-config-volume
          mountPath: /etc/xroad/
---
apiVersion: v1
kind: Service
metadata:
  name: cs-service
  namespace: xroad
  labels:
    app: central-server
spec:
  selector:
    app: central-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: admin
    port: 4000
    targetPort: 4000
    protocol: TCP
  type: ClusterIP
---
# Central Server Registration Service
apiVersion: v1
kind: Service
metadata:
  name: cs-registration-service
  namespace: xroad
  labels:
    app: central-server
spec:
  selector:
    app: central-server
  ports:
  - name: registration
    port: 8443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP
