apiVersion: v1
kind: Service
metadata:
  name: central-server
  namespace: xroad
  labels:
    app: central-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: central-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: central-server-config-pvc
  namespace: xroad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: xroad-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: central-server-data-pvc
  namespace: xroad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: xroad-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-server
  namespace: xroad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-server
  template:
    metadata:
      labels:
        app: central-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-1
      containers:
        - name: central-server
          image: niis/xroad-central-server:noble-7.7.0
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: XROAD_ADMIN_USER
              value: "admin"
            - name: XROAD_ADMIN_PASSWORD
              value: "admin123"
            - name: XROAD_DB_HOST
              value: "postgresql"
            - name: XROAD_DB_PORT
              value: "5432"
            - name: XROAD_DB_PWD
              value: "xroad123"
            - name: XROAD_DATABASE_NAME
              value: "xroad"
          volumeMounts:
            - name: xroad-config
              mountPath: /etc/xroad
            - name: xroad-data
              mountPath: /var/lib/xroad
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: xroad-config
          persistentVolumeClaim:
            claimName: central-server-config-pvc
        - name: xroad-data
          persistentVolumeClaim:
            claimName: central-server-data-pvc
