services:
  ss1:
    image: ghcr.io/nordic-institute/xrddev-securityserver:latest
    container_name: ss1-standalone
    environment:
      - XROAD_TOKEN_PIN=Secret1234
      - PROXY_JMX_PORT=4399
      - SIGNER_JMX_PORT=4398
    ports:
      - "4000:4000"   # Frontend UI
      - "4310:8080"   # Proxy port
      - "4320:5432"   # Database
      - "4390:9999"   # Proxy debug port
      - "4391:9998"   # Signer debug port
      - "4392:9997"   # Proxy UI debug port
      - "4393:9996"   # Conf Client debug port
      - "4399:4399"   # Proxy JMX port
      - "4398:4398"   # Signer JMX port
    volumes:
      - ss1_data:/var/lib/xroad
      - ss1_config:/etc/xroad
      - ss1_postgres:/var/lib/postgresql/16/main
      - ss1_softhsm:/var/lib/softhsm/tokens
      - ./init-token-and-run-entrypoint.sh:/usr/local/bin/init-token-and-run-entrypoint.sh:ro
    entrypoint: [ "/usr/local/bin/init-token-and-run-entrypoint.sh" ]
    restart: unless-stopped
    healthcheck:
      interval: 10s
      retries: 30
      timeout: 5s
      test: [ "CMD", "curl", "-f", "-k", "https://localhost:4000" ]
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 2560M

volumes:
  ss1_data:
    driver: local
  ss1_config:
    driver: local
  ss1_postgres:
    driver: local
  ss1_softhsm:
    driver: local
