---
# Default values for central-server.

image:
  repository: xroad-centralserver
  pullPolicy: Always
  tag: "7.6.0"

nameOverride: ""
fullnameOverride: ""

# Central Server configuration
centralServer:
  # Instance identifier for the central server
  instanceIdentifier: "EE"
  # Central server admin port
  adminPort: 4000
  # Central server management service port
  managementPort: 4001
  # Central server registration service port  
  registrationPort: 4002

# Database configuration
database:
  # Use external PostgreSQL or internal
  external:
    enabled: false
    host: ""
    port: 5432
    name: "centerui_production"
    user: "centerui"
    secretName: ""
  # Internal PostgreSQL configuration
  internal:
    enabled: true
    # PostgreSQL version
    version: "16"
    # Database storage size
    storageSize: "10Gi"
    # Database storage class
    storageClass: ""

# Service configuration
service:
  type: NodePort
  # NodePort values
  adminNodePort: 30060
  managementNodePort: 30061
  registrationNodePort: 30062

# Resources
resources:
  limits:
    cpu: 2000m
    memory: 4000Mi
  requests:
    cpu: 500m
    memory: 2000Mi

# Environment variables
env:
  # X-Road token PIN for autologin
  tokenPIN: ""
  # Admin user credentials
  adminUser: "xrd-sys"
  adminPassword: "secret"

# Persistence
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

# Security context
securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

# Pod security context
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Network policy
applyNetworkPolicy: false
adminAllowedIPRange: "0.0.0.0/0"

# Custom configuration files
filesData: ""
# filesData: |
#   custom-config.ini: |
#     [admin-service]
#     global-configuration-generation-rate-in-seconds = 10

# Custom volumes
volumes: ""
# volumes: |
#   - name: custom-config
#     configMap:
#       name: {{ include "central-server.fullname" . }}-files
#       items:
#       - key: custom-config.ini
#         path: custom-config.ini

# Custom volume mounts
volumeMounts: []
# volumeMounts:
# - name: custom-config
#   mountPath: "/etc/xroad/conf.d/custom-config.ini"
#   subPath: "custom-config.ini"
#   readOnly: true
