---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ include "pgop.fullname" . }}
  labels:
    {{- include "pgop.labels" . | nindent 4 }}
spec:
  {{- with .Values.clone }}
  clone:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  allowedSourceRanges: []
  numberOfInstances: {{ .Values.numberOfInstances }}
  postgresql:
    version: "{{ .Values.postgresql.version }}"
    parameters:
      max_connections: "{{ .Values.postgresql.max_connections }}"
      password_encryption: "{{ .Values.postgresql.password_encryption }}"
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  teamId: {{ .Values.team }}
  users:
    postgres: []
  volume:
    {{- toYaml .Values.volume | nindent 4 }}
  patroni:
    {{- toYaml .Values.patroni | nindent 4 }}
  {{- with concat .Values.env .Values.envClone }}
  env:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  additionalVolumes:
  # Using correct timezone
  - name: "localtime"
    mountPath: "/etc/localtime"
    volumeSource:
      hostPath:
        path: "/etc/localtime"
  {{- if .Values.additionalVolumes }}
  {{- toYaml .Values.additionalVolumes | nindent 2 }}
  {{- end }}
