---
# Default values for pgop.

# 3 is minimum if synchronous_mode_strict==true
numberOfInstances: 3

team: xtee

applyNetworkPolicy: false
# Allowed namespaces for network policies
postgresOperatorNamespace: postgres-operator
prometheusNamespace: prometheus
dbClientLabels:
- app.kubernetes.io/instance: xrd-security-server

postgresql:
  version: 16
  max_connections: 200
  password_encryption: scram-sha-256

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 500Mi
  # requests:
  #   cpu: 200m
  #   memory: 100Mi

volume:
  size: 2000Mi
  # iops: 3000
  # throughput: 125

patroni:
  # ttl: 30
  # loop_wait: 10
  # retry_timeout: 10
  synchronous_mode: true
  synchronous_mode_strict: true
  synchronous_node_count: 1
  maximum_lag_on_failover: 0

# Uncomment "clone" configuration when you need to restore instead of creating new cluster
clone: {}
  # # With UID
  # # UID can be found in S3 bucket wal path name
  # # For example: s3://pgop-xtee/spilo/xrd-pgop/98565c21-9ea8-475f-9cde-bbbd1cbe3519/wal/12/
  # # You may want to use helm parameter instead:
  # # helm upgrade --install -n xtee xrd-pgop helm/pgop -f pgop-values-uid-restore.yaml --set clone.uid=caf118ed-0f84-4c01-9788-3b4ff7051949
  # uid: "98565c21-9ea8-475f-9cde-bbbd1cbe3519"
  # cluster: "xrd-pgop"
  # timestamp: "2100-01-01T00:00:00+00:00"

  # # Without UID
  # cluster: "xrd-pgop"
  # timestamp: "2100-01-01T00:00:00+00:00"

# Uncomment "clone" restore configuration when you need to restore instead of creating new cluster
envClone: []
# # Without UID
# - name: CLONE_WAL_S3_BUCKET
#   value: "pgop-xtee"
# - name: CLONE_WAL_BUCKET_SCOPE_PREFIX
#   value: ""
# - name: CLONE_WAL_BUCKET_SCOPE_SUFFIX
#   value: ""

# # Common parameters
# - name: CLONE_USE_WALG_RESTORE
#   value: "true"
# - name: CLONE_AWS_ACCESS_KEY_ID
#   value: "minio"
# - name: CLONE_AWS_SECRET_ACCESS_KEY
#   value: "miniopass"
# - name: CLONE_AWS_S3_FORCE_PATH_STYLE
#   value: "true"
# - name: CLONE_AWS_ENDPOINT
#   value: "http://xrd-local-minio:9000"

# Uncomment to configure backup
env: []
# # Without UID
# - name: WAL_S3_BUCKET
#   value: "pgop-xtee"
# - name: WAL_BUCKET_SCOPE_PREFIX
#   value: ""
# - name: WAL_BUCKET_SCOPE_SUFFIX
#   value: ""

# # Common parameters
# - name: USE_WALG_BACKUP
#   value: "true"
# - name: USE_WALG_RESTORE
#   value: "true"
# - name: BACKUP_SCHEDULE
#   value: "0 6 * * *"
# - name: AWS_ACCESS_KEY_ID
#   value: "minio"
# - name: AWS_SECRET_ACCESS_KEY
#   value: "miniopass"
# - name: AWS_S3_FORCE_PATH_STYLE
#   value: "true"
# - name: AWS_ENDPOINT
#   value: "http://xrd-local-minio:9000"
# - name: BACKUP_NUM_TO_RETAIN
#   value: "3"

additionalVolumes: []

nameOverride: ""
fullnameOverride: ""
