---
# X-Road deployment configuration for 3 worker nodes cluster

# Global configuration
global:
  instanceIdentifier: "EE"
  namespace: "xroad"

# Central Server configuration - Deploy on worker-1
centralServer:
  enabled: true
  image:
    repository: niis/xroad-central-server
    tag: "noble-7.7.0"
    pullPolicy: Always

  ports:
    admin: 4000
    management: 4001
    registration: 4002
    postgres: 5432

  service:
    type: NodePort
    adminNodePort: 30060
    managementNodePort: 30061
    registrationNodePort: 30062

  resources:
    limits:
      cpu: 2000m
      memory: 4000Mi
    requests:
      cpu: 500m
      memory: 2000Mi

  persistence:
    enabled: true
    storageClass: "xroad-storage"
    size: 10Gi

  # Node affinity to deploy on worker-1
  nodeSelector:
    kubernetes.io/hostname: k8s-worker-1

  env:
    tokenPIN: "1234"
    adminUser: "xrd-sys"
    adminPassword: "secret"

# Security Server cluster configuration
securityServer:
  enabled: true
  image:
    repository: niis/xroad-security-server-sidecar
    primaryTag: "7.7.0-primary"
    secondaryTag: "7.7.0-secondary"
    pullPolicy: Always

  # Deploy primary on worker-2, secondary on worker-3
  secondaryReplicaCount: 1

  # Node selectors for specific deployment
  primaryNodeSelector:
    kubernetes.io/hostname: k8s-worker-2

  secondaryNodeSelector:
    kubernetes.io/hostname: k8s-worker-3

  service:
    type: NodePort
    adminNodePort: 30050
    consumerNodePort: 30051
    transportNodePort: 30052
    ocspNodePort: 30053
    healthNodePort: 30054

  resources:
    limits:
      cpu: 2000m
      memory: 4000Mi
    requests:
      cpu: 500m
      memory: 2000Mi

  persistence:
    etcVolumeSize: 100Mi
    libVolumeSize: 1000Mi

# PostgreSQL Operator configuration
postgresOperator:
  enabled: false # Disabled because we install PostgreSQL Operator separately

postgresOperatorUI:
  enabled: false # Disabled to avoid conflicts

# PostgreSQL cluster configuration - Disabled in X-Road chart
# We use external PostgreSQL HA cluster managed by PostgreSQL Operator
postgresql:
  enabled: false # Disabled because we use external PostgreSQL HA

# External database configuration for X-Road
externalDatabase:
  enabled: true
  host: "xroad-postgres-ha.xroad.svc.cluster.local"  # Master service (read/write)
  port: 5432
  database: "xroad"
  username: "xroad"
  password: "xroad123"  # Sẽ được override bởi operator-created secret
  sslMode: "prefer"
  
  # Connection pool settings
  maxConnections: 100
  connectionTimeout: 30
  idleTimeout: 300
  
  # Replica service for read-only operations (optional)
  replicaHost: "xroad-postgres-ha-repl.xroad.svc.cluster.local"
  replicaPort: 5432

# Network policies
networkPolicy:
  enabled: false
  adminAllowedIPRange: "0.0.0.0/0"

# Secrets configuration
secrets:
  envSecretName: ""
  envSecret:
    tokenPIN: "1234"
    adminUserName: "xrd-sys"
    adminUserPassword: "secret"

  sshSecretName: ""
  sshSecret:
    privateKey: ""
    publicKey: ""

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: xroad.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: central-server
            port: 4000
  tls: []

# Monitoring configuration
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s

# Pod Anti-Affinity for High Availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - xroad-central-server
          topologyKey: "kubernetes.io/hostname"
