---
# X-Road deployment configuration for 3 worker nodes cluster

# Global configuration
global:
  instanceIdentifier: "EE"
  namespace: "xroad"

# Central Server configuration - Deploy on worker-1
centralServer:
  enabled: true
  image:
    repository: xroad-centralserver
    tag: "7.6.0"
    pullPolicy: Always

  ports:
    admin: 4000
    management: 4001
    registration: 4002
    postgres: 5432

  service:
    type: NodePort
    adminNodePort: 30060
    managementNodePort: 30061
    registrationNodePort: 30062

  resources:
    limits:
      cpu: 2000m
      memory: 4000Mi
    requests:
      cpu: 500m
      memory: 2000Mi

  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi

  # Node affinity to deploy on worker-1
  nodeSelector:
    kubernetes.io/hostname: k8s-worker-1

  env:
    tokenPIN: "1234"
    adminUser: "xrd-sys"
    adminPassword: "secret"

# Security Server cluster configuration
securityServer:
  enabled: true
  image:
    repository: niis/xroad-security-server-sidecar
    primaryTag: "7.6.1-primary-ee"
    secondaryTag: "7.6.1-secondary-ee"
    pullPolicy: Always

  # Deploy primary on worker-2, secondary on worker-3
  secondaryReplicaCount: 1

  service:
    type: NodePort
    adminNodePort: 30050
    consumerNodePort: 30051
    transportNodePort: 30052
    ocspNodePort: 30053
    healthNodePort: 30054

  resources:
    limits:
      cpu: 2000m
      memory: 4000Mi
    requests:
      cpu: 500m
      memory: 2000Mi

  persistence:
    etcVolumeSize: 100Mi
    libVolumeSize: 1000Mi

# PostgreSQL configuration - Using Patroni HA
# Patroni is installed separately with 3 replicas across all workers
postgresql:
  enabled: false # Disabled because we use Patroni HA

# Patroni PostgreSQL HA configuration
patroni:
  enabled: true
  service:
    name: "postgres-ha"
    port: 5432
  database:
    name: "xroad"
    user: "xroad"
    password: "xroad123"
  connectionString: "postgresql://xroad:xroad123@postgres-ha.xroad.svc.cluster.local:5432/xroad"

# Network policies
networkPolicy:
  enabled: false
  adminAllowedIPRange: "0.0.0.0/0"

# Secrets configuration
secrets:
  envSecretName: ""
  envSecret:
    tokenPIN: "1234"
    adminUserName: "xrd-sys"
    adminUserPassword: "secret"

  sshSecretName: ""
  sshSecret:
    privateKey: ""
    publicKey: ""

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: xroad.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: central-server
            port: 4000
  tls: []

# Monitoring configuration
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s

# Pod Anti-Affinity for High Availability
podAntiAffinity:
  enabled: true
  type: "preferredDuringSchedulingIgnoredDuringExecution"
