{{- if .Values.postgresql.enabled }}
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ include "xroad.postgresql.fullname" . }}
  labels:
    {{- include "xroad.labels" . | nindent 4 }}
spec:
  teamId: "xroad"
  volume:
    size: {{ .Values.postgresql.persistence.size }}
    {{- if .Values.postgresql.persistence.storageClass }}
    storageClass: {{ .Values.postgresql.persistence.storageClass }}
    {{- end }}
  
  numberOfInstances: 3
  
  postgresql:
    version: "15"
    parameters:
      max_connections: "200"
      shared_preload_libraries: "pg_stat_statements"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: "all"
  
  databases:
    {{ .Values.postgresql.database.name }}: {{ .Values.postgresql.database.user }}
  
  users:
    {{ .Values.postgresql.database.user }}:
      - superuser
      - createdb
  
  resources:
    {{- toYaml .Values.postgresql.resources | nindent 4 }}
  
  {{- if .Values.postgresql.backup.enabled }}
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xroad.postgresql.fullname" . }}-credentials
  labels:
    {{- include "xroad.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.database.user | b64enc | quote }}
  password: {{ .Values.postgresql.database.password | b64enc | quote }}
{{- if .Values.postgresql.backup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xroad.postgresql.fullname" . }}-backup-credentials
  labels:
    {{- include "xroad.labels" . | nindent 4 }}
type: Opaque
data:
  ACCESS_KEY_ID: {{ .Values.postgresql.backup.s3.accessKey | b64enc | quote }}
  SECRET_ACCESS_KEY: {{ .Values.postgresql.backup.s3.secretKey | b64enc | quote }}
{{- end }}
{{- end }}
