# Central Server Database - PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-postgres-pvc
  namespace: xroad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-postgres
  namespace: xroad
  labels:
    app: cs-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-postgres
  template:
    metadata:
      labels:
        app: cs-postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node-1  # Chỉ định worker node 1
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: xroad_cs
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cs-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs-db-secret
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        - name: postgres-hba
          mountPath: /etc/postgresql/pg_hba.conf
          subPath: pg_hba.conf
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: cs-postgres-pvc
      - name: postgres-config
        configMap:
          name: postgres-config
      - name: postgres-hba
        configMap:
          name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: cs-postgres-service
  namespace: xroad
  labels:
    app: cs-postgres
spec:
  selector:
    app: cs-postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
