# Security Server Database Primary (Read/Write) - PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-postgres-primary
  namespace: xroad
  labels:
    app: ss-postgres-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ss-postgres-primary
  template:
    metadata:
      labels:
        app: ss-postgres-primary
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-2  # Chỉ định worker node 2
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: xroad_ss
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ss-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ss-db-secret
              key: password
        - name: POSTGRES_REPLICATION_USER
          value: replicator
        - name: POSTGRES_REPLICATION_PASSWORD
          value: replicator123
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_INITDB_ARGS
          value: "--auth-host=md5 --auth-local=trust"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        - name: postgres-hba
          mountPath: /etc/postgresql/pg_hba.conf
          subPath: pg_hba.conf
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
      volumes:
      - name: postgres-storage
        hostPath:
          path: /var/lib/postgresql/ss-primary-data
          type: DirectoryOrCreate
      - name: postgres-config
        configMap:
          name: postgres-config
      - name: postgres-hba
        configMap:
          name: postgres-config
      - name: init-script
        configMap:
          name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: ss-postgres-primary-service
  namespace: xroad
  labels:
    app: ss-postgres-primary
spec:
  selector:
    app: ss-postgres-primary
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
