---
apiVersion: v2
name: xroad
description: A complete X-Road deployment with Central Server and Security Server cluster

type: application
version: 0.1.0
appVersion: "7.6.0"

dependencies:
- name: postgres-operator
  version: "1.15.0"
  repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
  condition: postgresOperator.enabled
- name: postgres-operator-ui
  version: "1.15.0"
  repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui"
  condition: postgresOperatorUI.enabled
