{{- if not .Values.dbSecretName }}
{{- $_ := required "dbSecret.password is a required value" .Values.dbSecret.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "security-server.fullname" . }}-db
  labels:
    {{- include "security-server-primary.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: "{{ .Values.dbSecret.password }}"
{{- end }}
{{- if not .Values.envSecretName }}
{{- $_ := required "envSecret.tokenPIN is a required value" .Values.envSecret.tokenPIN }}
{{- $_ := required "envSecret.adminUserName is a required value" .Values.envSecret.adminUserName }}
{{- $_ := required "envSecret.adminUserPassword is a required value" .Values.envSecret.adminUserPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "security-server.fullname" . }}-env
  labels:
    {{- include "security-server-primary.labels" . | nindent 4 }}
type: Opaque
stringData:
  # PIN for autologin
  XROAD_TOKEN_PIN: "{{ .Values.envSecret.tokenPIN }}"
  XROAD_ADMIN_USER: "{{ .Values.envSecret.adminUserName }}"
  XROAD_ADMIN_PASSWORD: "{{ .Values.envSecret.adminUserPassword }}"
{{- end }}
{{- if not .Values.sshSecretName }}
{{- $_ := required "sshSecret.privateKey is a required value" .Values.sshSecret.privateKey }}
{{- $_ := required "sshSecret.publicKey is a required value" .Values.sshSecret.publicKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "security-server.fullname" . }}-ssh
  labels:
    {{- include "security-server-primary.labels" . | nindent 4 }}
type: Opaque
stringData:
  private-key: |
    {{- .Values.sshSecret.privateKey | nindent 4 }}
  public-key: |
    {{- .Values.sshSecret.publicKey | nindent 4 }}
{{- end }}
