---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-server.fullname" . }}-primary
  labels:
    {{- include "security-server-primary.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "security-server-primary.selectorLabels" . | nindent 4 }}
  clusterIP: None
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    name: ssh
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-server.fullname" . }}-admin
  labels:
    {{- include "security-server-primary.labels" . | nindent 4 }}
  {{- with .Values.metalLBIPs }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ . }}
    metallb.universe.tf/allow-shared-ip: "security-server-{{ . }}"
  {{- end }}
spec:
  selector:
    {{- include "security-server-primary.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    name: xroad-admin
    {{- with .Values.adminNodePort }}
    nodePort: {{ . }}
    {{- end }}
  type: {{ .Values.serviceType | default "NodePort" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-server.fullname" . }}-consumer
  labels:
    {{- include "security-server-secondary.labels" . | nindent 4 }}
  {{- with .Values.metalLBIPs }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ . }}
    metallb.universe.tf/allow-shared-ip: "security-server-{{ . }}"
  {{- end }}
spec:
  selector:
    {{- include "security-server-secondary.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.consumerPort | default 443 }}
    targetPort: {{ .Values.consumerTargetPort | default 443 }}
    protocol: TCP
    name: xroad-message-protocol
    {{- with .Values.consumerNodePort }}
    nodePort: {{ . }}
    {{- end }}
  type: {{ .Values.serviceType | default "NodePort" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-server.fullname" . }}-transport
  labels:
    {{- include "security-server-secondary.labels" . | nindent 4 }}
  {{- with .Values.metalLBIPs }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ . }}
    metallb.universe.tf/allow-shared-ip: "security-server-{{ . }}"
  {{- end }}
spec:
  selector:
    {{- include "security-server-secondary.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500
    name: xroad-message-transport
    {{- with .Values.transportNodePort }}
    nodePort: {{ . }}
    {{- end }}
  - protocol: TCP
    port: 5577
    targetPort: 5577
    name: xroad-ocsp
    {{- with .Values.ocspNodePort }}
    nodePort: {{ . }}
    {{- end }}
  - protocol: TCP
    port: 5588
    targetPort: 5588
    name: health
    {{- with .Values.healthNodePort }}
    nodePort: {{ . }}
    {{- end }}
  type: {{ .Values.serviceType | default "NodePort" }}
